#!/usr/bin/env bash

# Source files for implantation into new ISO (ks.cfg, etc.)
# This needs to be an absolute path, not a relative path.
# Also serves as the base for all relative paths defined below.
# Default is pwd 
#SRCDIR=""

# Source Media ISO Location
# ISOSRCDIR=""

# OEM Source Media File Name
#OEMSRCISO="rhel-8.7-x86_64-dvd.iso"

# Create new full boot ISO
#CREATEBOOTISO="true"

# Create OEMDRV volume ISO
#CREATEOEMDRVISO="true"

# FIPS Mode
#ENABLEFIPS="true"

# Write plaintext passwords to files
# Generally uneeded, but useful for console testing.
# NOT Recommended to write plaintext passwords out.
# WRITEPASSWDS="false"

# Root password - Specify a password in plain text.
# Generally uneeded, but useful for console testing.
# NOT Recommended to write plaintext passwords out.
#password=""

